import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <h1>Homepage</h1>
      <Image src="/logo.png" alt="SDA Logo" width={72} height={16} />
    </div>
  );
}
